In [1]:
import pandas as pd
import numpy as np

# Importando data

In [2]:
data = pd.read_csv('owid-energy-data.csv')

In [3]:
data.describe()

,year,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
count,22012.000000,1.812300e+04,1.111300e+04,1747.000000,2687.000000,2302.000000,2767.000000,5275.000000,5527.000000,5492.000000,...,6849.000000,4035.000000,2413.000000,4639.000000,4744.000000,7065.000000,7996.000000,4065.000000,6886.000000,4101.000000
mean,1974.213247,1.053096e+08,3.585114e+11,46.091694,2.719074,133.558459,38.068209,64.716800,10.966685,1.954035,...,0.622750,0.210395,267.541206,7.314174,53.422938,62.811828,17.561153,232.108949,1.404910,0.651413
std,35.058653,4.640460e+08,2.411179e+12,274.616745,10.057018,264.707851,111.623148,201.043915,47.953561,5.274155,...,2.066186,0.643304,5940.944120,37.327922,273.255306,252.734217,101.693172,733.841324,4.489043,1.893820
min,1900.000000,1.833000e+03,1.642060e+08,-100.000000,-50.843000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-100.000000,-51.208000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1946.000000,1.712404e+06,1.365898e+10,-0.616500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,4.029000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1984.000000,6.991543e+06,4.167411e+10,8.179000,0.000000,15.482000,0.673000,0.146000,0.010000,0.062000,...,0.000000,0.000000,20.000000,0.000000,0.005000,0.000000,0.000000,0.051000,0.000000,0.003000
75%,2003.000000,2.557688e+07,1.744295e+11,26.508500,0.861500,165.266750,13.629500,34.289000,0.690000,1.577500,...,0.095000,0.018500,47.971000,0.315000,2.357750,2.101000,0.140000,45.523000,0.372000,0.268000
max,2022.000000,7.975105e+09,1.136302e+14,5659.328000,141.131000,2588.512000,1199.207000,2514.102000,677.570000,71.429000,...,40.000000,7.586000,242384.844000,665.413000,5487.600000,3219.852000,2139.230000,8422.012000,56.840000,26.157000

# Criando coluna fonte

In [4]:
data[data['country'].str.contains('\(')].country.unique()

array(['ASEAN (Ember)', 'Africa (EI)', 'Africa (Ember)', 'Africa (Shift)',
       'Asia & Oceania (EIA)', 'Asia (Ember)', 'Asia Pacific (EI)',
       'Asia and Oceania (Shift)', 'Australia and New Zealand (EIA)',
       'CIS (EI)', 'Central & South America (EIA)',
       'Central America (EI)', 'Central and South America (Shift)',
       'EU28 (Shift)', 'East Germany (EIA)', 'Eastern Africa (EI)',
       'Eurasia (EIA)', 'Eurasia (Shift)', 'Europe (EI)',
       'Europe (Ember)', 'Europe (Shift)', 'European Union (27)',
       'European Union (EIA)', 'G20 (Ember)', 'G7 (Ember)',
       'Hawaiian Trade Zone (EIA)', 'IEO - Africa (EIA)',
       'IEO - Middle East (EIA)', 'IEO OECD - Europe (EIA)',
       'Latin America and Caribbean (Ember)',
       'Mexico, Chile, and other OECD Americas (EIA)',
       'Micronesia (country)', 'Middle Africa (EI)', 'Middle East (EI)',
       'Middle East (EIA)', 'Middle East (Ember)', 'Middle East (Shift)',
       'Non-OECD (EI)', 'Non-OECD (EIA)', 'Non-OPEC (EI)',
       'Non-OPEC (EIA)', 'North America (EI)', 'North America (Ember)',
       'North America (Shift)', 'OECD (EI)', 'OECD (EIA)', 'OECD (Ember)',
       'OECD (Shift)', 'OECD - Asia And Oceania (EIA)',
       'OECD - Europe (EIA)', 'OECD - North America (EIA)', 'OPEC (EI)',
       'OPEC (EIA)', 'OPEC (Shift)', 'OPEC - Africa (EIA)',
       'OPEC - South America (EIA)', 'Oceania (Ember)',
       'Other Non-OECD - America (EIA)', 'Other Non-OECD - Asia (EIA)',
       'Other Non-OECD - Europe and Eurasia (EIA)', 'Persian Gulf (EIA)',
       'Persian Gulf (Shift)', 'South Korea and other OECD Asia (EIA)',
       'South and Central America (EI)', 'U.S. Pacific Islands (EIA)',
       'U.S. Territories (EIA)', 'United States Pacific Islands (Shift)',
       'United States Territories (Shift)', 'Wake Island (EIA)',
       'Wake Island (Shift)', 'West Germany (EIA)', 'Western Africa (EI)'],
      dtype=object)

In [5]:
data.insert(1, 'fonte', '')

In [6]:
data['fonte'] = data['country'].str.extract('.*\((.*)\).*')

In [7]:
data.head()

,country,fonte,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),Ember,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),Ember,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),Ember,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),Ember,2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),Ember,2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN

# Criando df por fonte

In [8]:
fonte = pd.DataFrame(data.fonte.unique(), columns = ['fonte'])
fonte = fonte.fillna('-')
data['fonte'] = data['fonte'].fillna('-')

In [9]:
fonte = list(fonte['fonte'])
fonte

['Ember', '-', 'EI', 'Shift', 'EIA', '27', 'country']

In [11]:
dfs = list(range(7))

In [12]:
for i in range(len(fonte)):
    dfs[i] = pd.DataFrame(data = data[data['fonte'] == fonte[i]].replace(0, np.nan).dropna(axis = 1, how = 'all'))

In [13]:
fonte

['Ember', '-', 'EI', 'Shift', 'EIA', '27', 'country']

In [14]:
ember = dfs[0]
paises = dfs[1]
ei = dfs[2]
shift = dfs[3]
eia = dfs[4]
vintesete = dfs[5]
country = dfs[6]

In [16]:
paises.to_csv('paises.csv')

In [18]:
paises.describe()

,year,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
count,18166.000000,1.795800e+04,1.111300e+04,1396.000000,1431.000000,1473.000000,1471.000000,2656.000000,2656.000000,2656.000000,...,2126.000000,1450.000000,1853.000000,1904.000000,2053.000000,2308.000000,2305.00000,2067.000000,2245.000000,1861.000000
mean,1972.159584,1.038116e+08,3.585114e+11,52.746303,3.307607,204.742842,46.301710,126.535436,12.255463,3.850120,...,1.764092,0.507821,277.240328,11.470961,78.294133,187.986694,26.20636,443.580902,3.728605,1.273358
std,35.595559,4.656392e+08,2.411179e+12,305.208669,11.322195,306.813785,126.944898,268.364710,48.459525,7.076723,...,3.326251,0.951850,6247.576990,47.807174,341.018729,411.932698,122.61742,973.542960,7.096300,2.594805
min,1900.000000,1.833000e+03,1.642060e+08,-100.000000,-50.843000,0.017000,0.001000,0.064000,0.010000,0.003000,...,0.001000,0.001000,-100.000000,-51.208000,0.001000,0.001000,0.00100,0.001000,0.001000,0.001000
25%,1942.000000,1.713595e+06,1.365898e+10,-1.205500,-0.009000,16.702000,0.703500,6.072750,0.090000,0.433250,...,0.033000,0.004000,6.396000,0.008000,0.090000,2.140000,0.05000,2.335500,0.098000,0.018000
50%,1982.000000,6.926826e+06,4.167411e+10,8.023000,0.184000,79.950000,3.645000,31.546000,0.440000,1.431000,...,0.393000,0.047500,21.268000,0.255000,1.598000,24.650500,0.45000,38.812000,0.923000,0.204000
75%,2002.000000,2.484284e+07,1.744295e+11,27.319250,2.033500,274.842000,22.779000,136.823750,3.310000,4.712250,...,2.128750,0.632750,50.862000,2.677750,16.178000,163.991000,4.53300,396.863500,4.167000,1.363000
max,2022.000000,7.975105e+09,1.136302e+14,5659.328000,141.131000,2588.512000,1199.207000,2514.102000,677.570000,71.429000,...,40.000000,7.586000,242384.844000,665.413000,5487.600000,3219.852000,2139.23000,8422.012000,56.840000,26.157000

In [21]:
paises[paises['country'] == 'Brazil']

,country,fonte,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
2853,Brazil,-,1900,BRA,18058538.0,1.571802e+10,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2854,Brazil,-,1901,BRA,18463951.0,1.728848e+10,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2855,Brazil,-,1902,BRA,18869255.0,1.729822e+10,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2856,Brazil,-,1903,BRA,19274237.0,1.764560e+10,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2857,Brazil,-,1904,BRA,19687910.0,1.798087e+10,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2971,Brazil,-,2018,BRA,210166592.0,2.965402e+12,15.988,32.936,1136.938,238.946,...,0.579,0.263,14.400,15.484,128.252,228.961,48.12,610.240,8.099,3.690
2972,Brazil,-,2019,BRA,211782880.0,NaN,10.687,25.537,1248.842,264.483,...,1.065,0.497,15.493,19.325,147.577,261.730,55.43,696.829,8.960,4.177
2973,Brazil,-,2020,BRA,213196304.0,NaN,-6.896,-18.240,1155.008,246.243,...,1.732,0.832,1.902,2.255,149.832,264.920,56.48,702.787,9.193,4.414
2974,Brazil,-,2021,BRA,214326224.0,NaN,-1.120,-2.757,1136.055,243.486,...,2.528,1.228,26.705,39.317,189.149,333.604,71.50,882.529,10.791,5.297
2975,Brazil,-,2022,BRA,215313504.0,NaN,-0.631,-1.535,1123.715,241.951,...,3.889,2.109,12.929,23.675,212.824,371.551,80.00,988.440,11.750,5.714