In [164]:
import pandas as pd
import numpy as np

# Importando data

In [165]:
data = pd.read_csv('owid-energy-data.csv')

In [166]:
data.describe()

,year,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
count,22012.000000,1.812300e+04,1.111300e+04,1747.000000,2687.000000,2302.000000,2767.000000,5275.000000,5527.000000,5492.000000,...,6849.000000,4035.000000,2413.000000,4639.000000,4744.000000,7065.000000,7996.000000,4065.000000,6886.000000,4101.000000
mean,1974.213247,1.053096e+08,3.585114e+11,46.091694,2.719074,133.558459,38.068209,64.716800,10.966685,1.954035,...,0.622750,0.210395,267.541206,7.314174,53.422938,62.811828,17.561153,232.108949,1.404910,0.651413
std,35.058653,4.640460e+08,2.411179e+12,274.616745,10.057018,264.707851,111.623148,201.043915,47.953561,5.274155,...,2.066186,0.643304,5940.944120,37.327922,273.255306,252.734217,101.693172,733.841324,4.489043,1.893820
min,1900.000000,1.833000e+03,1.642060e+08,-100.000000,-50.843000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-100.000000,-51.208000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1946.000000,1.712404e+06,1.365898e+10,-0.616500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,4.029000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1984.000000,6.991543e+06,4.167411e+10,8.179000,0.000000,15.482000,0.673000,0.146000,0.010000,0.062000,...,0.000000,0.000000,20.000000,0.000000,0.005000,0.000000,0.000000,0.051000,0.000000,0.003000
75%,2003.000000,2.557688e+07,1.744295e+11,26.508500,0.861500,165.266750,13.629500,34.289000,0.690000,1.577500,...,0.095000,0.018500,47.971000,0.315000,2.357750,2.101000,0.140000,45.523000,0.372000,0.268000
max,2022.000000,7.975105e+09,1.136302e+14,5659.328000,141.131000,2588.512000,1199.207000,2514.102000,677.570000,71.429000,...,40.000000,7.586000,242384.844000,665.413000,5487.600000,3219.852000,2139.230000,8422.012000,56.840000,26.157000

# Criando coluna fonte

In [167]:
data[data['country'].str.contains('\(')].country.unique()

array(['ASEAN (Ember)', 'Africa (EI)', 'Africa (Ember)', 'Africa (Shift)',
       'Asia & Oceania (EIA)', 'Asia (Ember)', 'Asia Pacific (EI)',
       'Asia and Oceania (Shift)', 'Australia and New Zealand (EIA)',
       'CIS (EI)', 'Central & South America (EIA)',
       'Central America (EI)', 'Central and South America (Shift)',
       'EU28 (Shift)', 'East Germany (EIA)', 'Eastern Africa (EI)',
       'Eurasia (EIA)', 'Eurasia (Shift)', 'Europe (EI)',
       'Europe (Ember)', 'Europe (Shift)', 'European Union (27)',
       'European Union (EIA)', 'G20 (Ember)', 'G7 (Ember)',
       'Hawaiian Trade Zone (EIA)', 'IEO - Africa (EIA)',
       'IEO - Middle East (EIA)', 'IEO OECD - Europe (EIA)',
       'Latin America and Caribbean (Ember)',
       'Mexico, Chile, and other OECD Americas (EIA)',
       'Micronesia (country)', 'Middle Africa (EI)', 'Middle East (EI)',
       'Middle East (EIA)', 'Middle East (Ember)', 'Middle East (Shift)',
       'Non-OECD (EI)', 'Non-OECD (EIA)', 'Non-OPEC (EI)',
       'Non-OPEC (EIA)', 'North America (EI)', 'North America (Ember)',
       'North America (Shift)', 'OECD (EI)', 'OECD (EIA)', 'OECD (Ember)',
       'OECD (Shift)', 'OECD - Asia And Oceania (EIA)',
       'OECD - Europe (EIA)', 'OECD - North America (EIA)', 'OPEC (EI)',
       'OPEC (EIA)', 'OPEC (Shift)', 'OPEC - Africa (EIA)',
       'OPEC - South America (EIA)', 'Oceania (Ember)',
       'Other Non-OECD - America (EIA)', 'Other Non-OECD - Asia (EIA)',
       'Other Non-OECD - Europe and Eurasia (EIA)', 'Persian Gulf (EIA)',
       'Persian Gulf (Shift)', 'South Korea and other OECD Asia (EIA)',
       'South and Central America (EI)', 'U.S. Pacific Islands (EIA)',
       'U.S. Territories (EIA)', 'United States Pacific Islands (Shift)',
       'United States Territories (Shift)', 'Wake Island (EIA)',
       'Wake Island (Shift)', 'West Germany (EIA)', 'Western Africa (EI)'],
      dtype=object)

In [168]:
data.insert(1, 'fonte', '')

In [169]:
data['fonte'] = data['country'].str.extract('.*\((.*)\).*')

In [170]:
data.head()

,country,fonte,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),Ember,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),Ember,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),Ember,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),Ember,2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),Ember,2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN

# Criando coluna sem fonte

In [171]:
data.insert(1, 'country2', data['country'])
data

,country,country2,fonte,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),ASEAN (Ember),Ember,2000,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),ASEAN (Ember),Ember,2001,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),ASEAN (Ember),Ember,2002,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),ASEAN (Ember),Ember,2003,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),ASEAN (Ember),Ember,2004,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22007,Zimbabwe,Zimbabwe,NaN,2018,ZWE,15052191.0,2.271535e+10,NaN,NaN,NaN,...,0.218,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
22008,Zimbabwe,Zimbabwe,NaN,2019,ZWE,15354606.0,NaN,NaN,NaN,NaN,...,0.364,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
22009,Zimbabwe,Zimbabwe,NaN,2020,ZWE,15669663.0,NaN,NaN,NaN,NaN,...,0.395,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
22010,Zimbabwe,Zimbabwe,NaN,2021,ZWE,15993525.0,NaN,NaN,NaN,NaN,...,0.498,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
22011,Zimbabwe,Zimbabwe,NaN,2022,ZWE,16320539.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [172]:
data['country2'] = data['country'].str.replace(r"\(.*\)", '').str.strip()

C:\Users\nawan\AppData\Local\Temp\ipykernel_10632\3993442352.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  data['country2'] = data['country'].str.replace(r"\(.*\)", '').str.strip()

In [173]:
data[data['country2'].str.contains('Europe')].country2.unique()

array(['Europe', 'European Union', 'IEO OECD - Europe', 'OECD - Europe',
       'Other Non-OECD - Europe and Eurasia'], dtype=object)

# Criando df por fonte

In [174]:
fonte = pd.DataFrame(data.fonte.unique(), columns = ['fonte'])
fonte = fonte.fillna('-')
data['fonte'] = data['fonte'].fillna('-')

In [175]:
fonte = list(fonte['fonte'])
fonte

['Ember', '-', 'EI', 'Shift', 'EIA', '27', 'country']

In [176]:
dfs = list(range(7))

In [177]:
for i in range(len(fonte)):
    dfs[i] = pd.DataFrame(data = data[data['fonte'] == fonte[i]].replace(0, np.nan).dropna(axis = 1, how = 'all'))

In [178]:
fonte

['Ember', '-', 'EI', 'Shift', 'EIA', '27', 'country']

In [179]:
ember = dfs[0]
paises = dfs[1]
ei = dfs[2]
shift = dfs[3]
eia = dfs[4]
vintesete = dfs[5]
country = dfs[6]

In [180]:
paises.to_csv('paises.csv')

In [181]:
paises.describe()

,year,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
count,18166.000000,1.795800e+04,1.111300e+04,1396.000000,1431.000000,1473.000000,1471.000000,2656.000000,2656.000000,2656.000000,...,2126.000000,1450.000000,1853.000000,1904.000000,2053.000000,2308.000000,2305.00000,2067.000000,2245.000000,1861.000000
mean,1972.159584,1.038116e+08,3.585114e+11,52.746303,3.307607,204.742842,46.301710,126.535436,12.255463,3.850120,...,1.764092,0.507821,277.240328,11.470961,78.294133,187.986694,26.20636,443.580902,3.728605,1.273358
std,35.595559,4.656392e+08,2.411179e+12,305.208669,11.322195,306.813785,126.944898,268.364710,48.459525,7.076723,...,3.326251,0.951850,6247.576990,47.807174,341.018729,411.932698,122.61742,973.542960,7.096300,2.594805
min,1900.000000,1.833000e+03,1.642060e+08,-100.000000,-50.843000,0.017000,0.001000,0.064000,0.010000,0.003000,...,0.001000,0.001000,-100.000000,-51.208000,0.001000,0.001000,0.00100,0.001000,0.001000,0.001000
25%,1942.000000,1.713595e+06,1.365898e+10,-1.205500,-0.009000,16.702000,0.703500,6.072750,0.090000,0.433250,...,0.033000,0.004000,6.396000,0.008000,0.090000,2.140000,0.05000,2.335500,0.098000,0.018000
50%,1982.000000,6.926826e+06,4.167411e+10,8.023000,0.184000,79.950000,3.645000,31.546000,0.440000,1.431000,...,0.393000,0.047500,21.268000,0.255000,1.598000,24.650500,0.45000,38.812000,0.923000,0.204000
75%,2002.000000,2.484284e+07,1.744295e+11,27.319250,2.033500,274.842000,22.779000,136.823750,3.310000,4.712250,...,2.128750,0.632750,50.862000,2.677750,16.178000,163.991000,4.53300,396.863500,4.167000,1.363000
max,2022.000000,7.975105e+09,1.136302e+14,5659.328000,141.131000,2588.512000,1199.207000,2514.102000,677.570000,71.429000,...,40.000000,7.586000,242384.844000,665.413000,5487.600000,3219.852000,2139.23000,8422.012000,56.840000,26.157000

In [182]:
paises[paises['country'] == 'Brazil']

,country,country2,fonte,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
2853,Brazil,Brazil,-,1900,BRA,18058538.0,1.571802e+10,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2854,Brazil,Brazil,-,1901,BRA,18463951.0,1.728848e+10,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2855,Brazil,Brazil,-,1902,BRA,18869255.0,1.729822e+10,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2856,Brazil,Brazil,-,1903,BRA,19274237.0,1.764560e+10,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2857,Brazil,Brazil,-,1904,BRA,19687910.0,1.798087e+10,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2971,Brazil,Brazil,-,2018,BRA,210166592.0,2.965402e+12,15.988,32.936,1136.938,...,0.579,0.263,14.400,15.484,128.252,228.961,48.12,610.240,8.099,3.690
2972,Brazil,Brazil,-,2019,BRA,211782880.0,NaN,10.687,25.537,1248.842,...,1.065,0.497,15.493,19.325,147.577,261.730,55.43,696.829,8.960,4.177
2973,Brazil,Brazil,-,2020,BRA,213196304.0,NaN,-6.896,-18.240,1155.008,...,1.732,0.832,1.902,2.255,149.832,264.920,56.48,702.787,9.193,4.414
2974,Brazil,Brazil,-,2021,BRA,214326224.0,NaN,-1.120,-2.757,1136.055,...,2.528,1.228,26.705,39.317,189.149,333.604,71.50,882.529,10.791,5.297
2975,Brazil,Brazil,-,2022,BRA,215313504.0,NaN,-0.631,-1.535,1123.715,...,3.889,2.109,12.929,23.675,212.824,371.551,80.00,988.440,11.750,5.714

In [183]:
fonte

['Ember', '-', 'EI', 'Shift', 'EIA', '27', 'country']

In [184]:
eia.country.unique()

array(['Asia & Oceania (EIA)', 'Australia and New Zealand (EIA)',
       'Central & South America (EIA)', 'East Germany (EIA)',
       'Eurasia (EIA)', 'European Union (EIA)',
       'Hawaiian Trade Zone (EIA)', 'IEO - Africa (EIA)',
       'IEO - Middle East (EIA)', 'IEO OECD - Europe (EIA)',
       'Mexico, Chile, and other OECD Americas (EIA)',
       'Middle East (EIA)', 'Non-OECD (EIA)', 'Non-OPEC (EIA)',
       'OECD (EIA)', 'OECD - Asia And Oceania (EIA)',
       'OECD - Europe (EIA)', 'OECD - North America (EIA)', 'OPEC (EIA)',
       'OPEC - Africa (EIA)', 'OPEC - South America (EIA)',
       'Other Non-OECD - America (EIA)', 'Other Non-OECD - Asia (EIA)',
       'Other Non-OECD - Europe and Eurasia (EIA)', 'Persian Gulf (EIA)',
       'South Korea and other OECD Asia (EIA)',
       'U.S. Pacific Islands (EIA)', 'U.S. Territories (EIA)',
       'Wake Island (EIA)', 'West Germany (EIA)'], dtype=object)

In [185]:
vintesete.country.unique()

array(['European Union (27)'], dtype=object)

In [186]:
shift.country.unique()

array(['Africa (Shift)', 'Asia and Oceania (Shift)',
       'Central and South America (Shift)', 'EU28 (Shift)',
       'Eurasia (Shift)', 'Europe (Shift)', 'Middle East (Shift)',
       'North America (Shift)', 'OECD (Shift)', 'OPEC (Shift)',
       'Persian Gulf (Shift)', 'United States Pacific Islands (Shift)',
       'United States Territories (Shift)', 'Wake Island (Shift)'],
      dtype=object)

In [187]:
ember.country.unique()

array(['ASEAN (Ember)', 'Africa (Ember)', 'Asia (Ember)',
       'Europe (Ember)', 'G20 (Ember)', 'G7 (Ember)',
       'Latin America and Caribbean (Ember)', 'Middle East (Ember)',
       'North America (Ember)', 'OECD (Ember)', 'Oceania (Ember)'],
      dtype=object)

In [188]:
ei.country.unique()

array(['Africa (EI)', 'Asia Pacific (EI)', 'CIS (EI)',
       'Central America (EI)', 'Eastern Africa (EI)', 'Europe (EI)',
       'Middle Africa (EI)', 'Middle East (EI)', 'Non-OECD (EI)',
       'Non-OPEC (EI)', 'North America (EI)', 'OECD (EI)', 'OPEC (EI)',
       'South and Central America (EI)', 'Western Africa (EI)'],
      dtype=object)

In [189]:
paises.country.unique()

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'American Samoa',
       'Angola', 'Antarctica', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Aruba', 'Asia', 'Australia', 'Austria', 'Azerbaijan',
       'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Cayman Islands', 'Central African Republic', 'Chad', 'Chile',
       'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus',
       'Czechia', 'Czechoslovakia', 'Democratic Republic of Congo',
       'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic',
       'East Timor', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia',
       'Europe', 'Falkland Islands', 'Faroe Islands', 'Fiji', 'Finland',
       'France', 'French Guiana', 'French Polynesia', 'Gabon', 'Gambia',
       'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland',
       'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'High-income countries',
       'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
       'Lesotho', 'Liberia', 'Libya', 'Lithuania', 'Low-income countries',
       'Lower-middle-income countries', 'Luxembourg', 'Macao',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Martinique', 'Mauritania', 'Mauritius', 'Mexico', 'Moldova',
       'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands',
       'Netherlands Antilles', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'North America',
       'North Korea', 'North Macedonia', 'Northern Mariana Islands',
       'Norway', 'Oceania', 'Oman', 'Pakistan', 'Palestine', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Qatar', 'Reunion', 'Romania', 'Russia',
       'Rwanda', 'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Serbia and Montenegro', 'Seychelles', 'Sierra Leone',
       'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
       'South Africa', 'South America', 'South Korea', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland',
       'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Togo',
       'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'USSR',
       'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States', 'United States Virgin Islands',
       'Upper-middle-income countries', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Venezuela', 'Vietnam', 'Western Sahara', 'World',
       'Yemen', 'Yugoslavia', 'Zambia', 'Zimbabwe'], dtype=object)

In [190]:
eia[eia['country2'] == 'European Union']

,country,country2,fonte,year,energy_cons_change_pct,energy_cons_change_twh,primary_energy_consumption
7006,European Union (EIA),European Union,EIA,1980,NaN,NaN,17760.348
7007,European Union (EIA),European Union,EIA,1981,-3.333,-591.975,17168.373
7008,European Union (EIA),European Union,EIA,1982,-0.765,-131.402,17036.971
7009,European Union (EIA),European Union,EIA,1983,0.112,19.113,17056.084
7010,European Union (EIA),European Union,EIA,1984,1.382,235.742,17291.826
7011,European Union (EIA),European Union,EIA,1985,2.969,513.459,17805.285
7012,European Union (EIA),European Union,EIA,1986,2.138,380.695,18185.980
7013,European Union (EIA),European Union,EIA,1987,1.822,331.275,18517.256
7014,European Union (EIA),European Union,EIA,1988,0.797,147.643,18664.898
7015,European Union (EIA),European Union,EIA,1989,-0.074,-13.760,18651.139
7016,European Union (EIA),European Union,EIA,1990,-1.551,-289.311,18361.828
7017,European Union (EIA),European Union,EIA,1991,-2.796,-513.316,17848.512
7018,European Union (EIA),European Union,EIA,1992,0.776,138.424,17986.936
7019,European Union (EIA),European Union,EIA,1993,-0.663,-119.180,17867.756
7020,European Union (EIA),European Union,EIA,1994,0.001,0.227,17867.982
7021,European Union (EIA),European Union,EIA,1995,2.814,502.844,18370.826
7022,European Union (EIA),European Union,EIA,1996,2.704,496.689,18867.516
7023,European Union (EIA),European Union,EIA,1997,-0.280,-52.791,18814.725
7024,European Union (EIA),European Union,EIA,1998,0.451,84.775,18899.500
7025,European Union (EIA),European Union,EIA,1999,-0.731,-138.193,18761.307
7026,European Union (EIA),European Union,EIA,2000,1.094,205.221,18966.527
7027,European Union (EIA),European Union,EIA,2001,2.495,473.133,19439.660
7028,European Union (EIA),European Union,EIA,2002,-0.528,-102.701,19336.959
7029,European Union (EIA),European Union,EIA,2003,1.761,340.574,19677.533
7030,European Union (EIA),European Union,EIA,2004,1.827,359.414,20036.947
7031,European Union (EIA),European Union,EIA,2005,0.188,37.762,20074.709
7032,European Union (EIA),European Union,EIA,2006,0.687,137.965,20212.674
7033,European Union (EIA),European Union,EIA,2007,-1.040,-210.225,20002.449
7034,European Union (EIA),European Union,EIA,2008,-0.042,-8.457,19993.992
7035,European Union (EIA),European Union,EIA,2009,-6.088,-1217.287,18776.705
7036,European Union (EIA),European Union,EIA,2010,3.928,737.613,19514.318
7037,European Union (EIA),European Union,EIA,2011,-3.037,-592.688,18921.631
7038,European Union (EIA),European Union,EIA,2012,-1.230,-232.645,18688.986
7039,European Union (EIA),European Union,EIA,2013,-0.543,-101.564,18587.422
7040,European Union (EIA),European Union,EIA,2014,-2.962,-550.541,18036.881
7041,European Union (EIA),European Union,EIA,2015,0.936,168.738,18205.619
7042,European Union (EIA),European Union,EIA,2016,0.762,138.682,18344.301
7043,European Union (EIA),European Union,EIA,2017,2.019,370.324,18714.625
7044,European Union (EIA),European Union,EIA,2018,-0.558,-104.447,18610.178
7045,European Union (EIA),European Union,EIA,2019,-1.954,-363.582,18246.596
7046,European Union (EIA),European Union,EIA,2020,-8.006,-1460.771,16785.824
7047,European Union (EIA),European Union,EIA,2021,5.021,842.814,17628.639

In [201]:
vintesete2 = vintesete[['country', 'country2', 'fonte', 'year', 'energy_cons_change_pct', 'energy_cons_change_twh', 'primary_energy_consumption']]
vintesete2

,country,country2,fonte,year,energy_cons_change_pct,energy_cons_change_twh,primary_energy_consumption
6883,European Union (27),European Union,27,1900,NaN,NaN,NaN
6884,European Union (27),European Union,27,1901,NaN,NaN,NaN
6885,European Union (27),European Union,27,1902,NaN,NaN,NaN
6886,European Union (27),European Union,27,1903,NaN,NaN,NaN
6887,European Union (27),European Union,27,1904,NaN,NaN,NaN
...,...,...,...,...,...,...,...
7001,European Union (27),European Union,27,2018,-0.100,-17.447,17467.557
7002,European Union (27),European Union,27,2019,-1.630,-284.727,17182.830
7003,European Union (27),European Union,27,2020,-7.450,-1280.202,15902.628
7004,European Union (27),European Union,27,2021,5.294,841.815,16744.443
7005,European Union (27),European Union,27,2022,-3.484,-583.336,16161.107

In [204]:
join = vintesete2.merge(eia[eia['country2'] == 'European Union'], how = 'inner', on = 'year')

In [205]:
join

,country_x,country2_x,fonte_x,year,energy_cons_change_pct_x,energy_cons_change_twh_x,primary_energy_consumption_x,country_y,country2_y,fonte_y,energy_cons_change_pct_y,energy_cons_change_twh_y,primary_energy_consumption_y
0,European Union (27),European Union,27,1980,-1.690,-279.551,16264.594,European Union (EIA),European Union,EIA,NaN,NaN,17760.348
1,European Union (27),European Union,27,1981,-2.872,-467.049,15797.545,European Union (EIA),European Union,EIA,-3.333,-591.975,17168.373
2,European Union (27),European Union,27,1982,-2.357,-372.414,15425.131,European Union (EIA),European Union,EIA,-0.765,-131.402,17036.971
3,European Union (27),European Union,27,1983,0.458,70.632,15495.763,European Union (EIA),European Union,EIA,0.112,19.113,17056.084
4,European Union (27),European Union,27,1984,3.041,471.243,15967.006,European Union (EIA),European Union,EIA,1.382,235.742,17291.826
5,European Union (27),European Union,27,1985,5.118,817.221,16784.227,European Union (EIA),European Union,EIA,2.969,513.459,17805.285
6,European Union (27),European Union,27,1986,1.443,242.229,17026.455,European Union (EIA),European Union,EIA,2.138,380.695,18185.980
7,European Union (27),European Union,27,1987,2.079,353.992,17380.447,European Union (EIA),European Union,EIA,1.822,331.275,18517.256
8,European Union (27),European Union,27,1988,0.839,145.871,17526.318,European Union (EIA),European Union,EIA,0.797,147.643,18664.898
9,European Union (27),European Union,27,1989,0.263,46.180,17572.498,European Union (EIA),European Union,EIA,-0.074,-13.760,18651.139
10,European Union (27),European Union,27,1990,-0.459,-80.609,17491.889,European Union (EIA),European Union,EIA,-1.551,-289.311,18361.828
11,European Union (27),European Union,27,1991,-0.451,-78.820,17413.068,European Union (EIA),European Union,EIA,-2.796,-513.316,17848.512
12,European Union (27),European Union,27,1992,-1.907,-332.074,17080.994,European Union (EIA),European Union,EIA,0.776,138.424,17986.936
13,European Union (27),European Union,27,1993,-0.769,-131.328,16949.666,European Union (EIA),European Union,EIA,-0.663,-119.180,17867.756
14,European Union (27),European Union,27,1994,-0.365,-61.889,16887.777,European Union (EIA),European Union,EIA,0.001,0.227,17867.982
15,European Union (27),European Union,27,1995,2.469,417.012,17304.789,European Union (EIA),European Union,EIA,2.814,502.844,18370.826
16,European Union (27),European Union,27,1996,3.060,529.443,17834.232,European Union (EIA),European Union,EIA,2.704,496.689,18867.516
17,European Union (27),European Union,27,1997,-0.387,-69.084,17765.148,European Union (EIA),European Union,EIA,-0.280,-52.791,18814.725
18,European Union (27),European Union,27,1998,1.028,182.557,17947.705,European Union (EIA),European Union,EIA,0.451,84.775,18899.500
19,European Union (27),European Union,27,1999,-0.462,-82.977,17864.729,European Union (EIA),European Union,EIA,-0.731,-138.193,18761.307
20,European Union (27),European Union,27,2000,0.753,134.484,17999.213,European Union (EIA),European Union,EIA,1.094,205.221,18966.527
21,European Union (27),European Union,27,2001,2.001,360.119,18359.332,European Union (EIA),European Union,EIA,2.495,473.133,19439.660
22,European Union (27),European Union,27,2002,-0.680,-124.781,18234.551,European Union (EIA),European Union,EIA,-0.528,-102.701,19336.959
23,European Union (27),European Union,27,2003,1.963,357.982,18592.533,European Union (EIA),European Union,EIA,1.761,340.574,19677.533
24,European Union (27),European Union,27,2004,1.412,262.508,18855.041,European Union (EIA),European Union,EIA,1.827,359.414,20036.947
25,European Union (27),European Union,27,2005,0.026,4.871,18859.912,European Union (EIA),European Union,EIA,0.188,37.762,20074.709
26,European Union (27),European Union,27,2006,0.772,145.689,19005.602,European Union (EIA),European Union,EIA,0.687,137.965,20212.674
27,European Union (27),European Union,27,2007,-1.227,-233.111,18772.490,European Union (EIA),European Union,EIA,-1.040,-210.225,20002.449
28,European Union (27),European Union,27,2008,-0.381,-71.541,18700.949,European Union (EIA),European Union,EIA,-0.042,-8.457,19993.992
29,European Union (27),European Union,27,2009,-5.960,-1114.543,17586.406,European Union (EIA),European Union,EIA,-6.088,-1217.287,18776.705
30,European Union (27),European Union,27,2010,4.065,714.857,18301.264,European Union (EIA),European Union,EIA,3.928,737.613,19514.318
31,European Union (27),European Union,27,2011,-2.989,-547.111,17754.152,European Union (EIA),European Union,EIA,-3.037,-592.688,18921.631
32,European Union (27),European Union,27,2012,-1.013,-179.865,17574.287,European Union (EIA),European Union,EIA,-1.230,-232.645,18688.986
33,European Union (27),European Union,27,2013,-0.806,-141.684,17432.604,European Union (EIA),European Union,EIA,-0.543,-101.564,18587.422
34,European Union (27),European Union,27,2014,-3.459,-602.959,16829.645,European Union (EIA),European Union,EIA,-2.962,-550.541,18036.881
35,European Union (27),European Union,27,2015,1.327,223.369,17053.014,European Union (EIA),European Union,EIA,0.936,168.738,18205.619
36,European Union (27),European Union,27,2016,1.093,186.420,17239.434,European Union (EIA),European Union,EIA,0.762,138.682,18344.301
37,European Union (27),European Union,27,2017,1.424,245.570,17485.004,European Union (EIA),European Union,EIA,2.019,370.324,18714.625
38,European Union (27),European Union,27,2018,-0.100,-17.447,17467.557,European Union (EIA),European Union,EIA,-0.558,-104.447,18610.178
39,European Union (27),European Union,27,2019,-1.630,-284.727,17182.830,European Union (EIA),European Union,EIA,-1.954,-363.582,18246.596
40,European Union (27),European Union,27,2020,-7.450,-1280.202,15902.628,European Union (EIA),European Union,EIA,-8.006,-1460.771,16785.824
41,European Union (27),European Union,27,2021,5.294,841.815,16744.443,European Union (EIA),European Union,EIA,5.021,842.814,17628.639